# Working with Numpy

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
import numpy as np 

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
# Casting normal python array to numpy array
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
## Making a two dimensional array using numpy
my_mat = [[1,2,3],[4,5,6], [7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Like the range function in python this will go from 0 to 10 not including 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Generate numpy arrays of zeros.The first number in the tuple represent the rows and the second the columns 
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
#Arrays of ones
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Linspace gives us an array of 100 evenly spaced elements between 0 and 5
# One Dimensional vector 
# Note this array has only one bracket pair so it is one dimensional 
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [13]:
#Identity matrix. Always prints a square array 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Generating random numbers in a numpy array
np.random.rand(6)

array([0.60262371, 0.48264236, 0.70170382, 0.35287705, 0.22756161,
       0.41674968])

In [16]:
#Two Dimensional numpy array with random values 
np.random.rand(5,5)

array([[0.35649231, 0.76698941, 0.79501741, 0.96509272, 0.83213173],
       [0.70128318, 0.12454849, 0.49943788, 0.78634022, 0.3428219 ],
       [0.1983283 , 0.64337442, 0.82874675, 0.59837542, 0.38838315],
       [0.2224234 , 0.96660493, 0.98143024, 0.49241915, 0.89937263],
       [0.69020523, 0.70243227, 0.91402913, 0.79968972, 0.41510491]])

In [19]:
# Generating random integer first two options specify the range of the random numbers. The last option(third) specifies the number 
# of random integers. Default is one 
np.random.randint(1,100, 20)

array([19, 19, 10, 18, 77, 92, 84, 33,  7, 90, 48, 73,  8, 66, 79, 93, 96,
       41, 51, 67])

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0,50, 10)
ranarr

array([ 8, 40,  7, 15, 49,  7, 28, 23, 41, 27])

In [26]:
# Reshaping array. Will return an error if the original array does not have enough elements to fill up the new dimensions. 
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([ 8, 40,  7, 15, 49,  7, 28, 23, 41, 27])

In [29]:
# Find max value in array 
ranarr.max()

49

In [35]:
# Find min value in array 
ranarr.min()

7

In [34]:
#Find the minimum and maximum value index location
# ranarr.argmin() for the minimum value index
ranarr.argmax()

4

In [32]:
ranarr

array([ 8, 40,  7, 15, 49,  7, 28, 23, 41, 27])

In [36]:
# .shape returns the shape of the array. In this particular case the 10 comma shows that this array is one dimensional as it contains only one row
ranarr.shape

(10,)

In [38]:
# reshape array into dimensional array
ranarr.reshape(2,5)

array([[ 8, 40,  7, 15, 49],
       [ 7, 28, 23, 41, 27]])

In [40]:
# find datatype of array
ranarr.dtype

dtype('int32')