In [1]:
# Working with Numpy

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
import numpy as np 

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
# Casting normal python array to numpy array
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
## Making a two dimensional array using numpy
my_mat = [[1,2,3],[4,5,6], [7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Like the range function in python this will go from 0 to 10 not including 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Generate numpy arrays of zeros.The first number in the tuple represent the rows and the 
np.zeros((5,5))